"""Crawler4j Contracts - Core <-> SDK 共享契约包。

本包只承载稳定契约类型，不包含运行时实现。
"""

from crawler4j_contracts.context import (
    BBox,
    ClickCaptchaDebugInfo,
    ClickCaptchaMatchResult,
    ClickCaptchaOrderedTarget,
    EnvCandidate,
    HttpClient,
    ImageInput,
    Point,
    SliderCaptchaDebugInfo,
    SliderCaptchaMatchResult,
    TaskContext,
    ToolSpec,
    ToolsCapability,
)
from crawler4j_contracts.candidate_query import EnvCandidates
from crawler4j_contracts.database import DatabaseClient, DatabaseExecutor
from crawler4j_contracts.decorators import (
    CRAWLER4J_META_ATTR,
    HOST_RESERVED_DATA_FIELDS,
    MANAGED_DATASET_RESERVED_DATA_FIELDS,
    Crawler4jMeta,
    DataTableIndexSpec,
    InjectSpec,
    ObjectInjectAnnotation,
    ObjectParamAnnotation,
    ParameterOptionSpec,
    ParameterSpec,
    component,
    data_query,
    data_table,
    env_cleanup_candidates,
    env_candidates,
    interface,
    object_inject,
    object_param,
    page,
    page_action,
    workflow,
)
from crawler4j_contracts.lifecycle import TaskOutcome, TaskOutcomeStatus, WorkflowLifecycleInfo
from crawler4j_contracts.result import TaskResult

__all__ = [
    "CRAWLER4J_META_ATTR",
    "HOST_RESERVED_DATA_FIELDS",
    "MANAGED_DATASET_RESERVED_DATA_FIELDS",
    "Crawler4jMeta",
    "DataTableIndexSpec",
    "InjectSpec",
    "ObjectInjectAnnotation",
    "ObjectParamAnnotation",
    "ParameterOptionSpec",
    "ParameterSpec",
    "component",
    "data_query",
    "data_table",
    "env_cleanup_candidates",
    "env_candidates",
    "EnvCandidates",
    "interface",
    "object_inject",
    "object_param",
    "page",
    "page_action",
    "workflow",
    "TaskContext",
    "TaskOutcome",
    "TaskOutcomeStatus",
    "TaskResult",
    "WorkflowLifecycleInfo",
    "HttpClient",
    "ImageInput",
    "BBox",
    "Point",
    "ToolSpec",
    "ToolsCapability",
    "DatabaseClient",
    "DatabaseExecutor",
    "SliderCaptchaDebugInfo",
    "SliderCaptchaMatchResult",
    "ClickCaptchaDebugInfo",
    "ClickCaptchaOrderedTarget",
    "ClickCaptchaMatchResult",
    "EnvCandidate",
]
